# Generated by Django 2.0.4 on 2018-04-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('save_at', models.DateTimeField(auto_now_add=True)),
                ('send_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiMetro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('save_at', models.DateTimeField(auto_now_add=True)),
                ('send_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('save_at', models.DateTimeField(auto_now_add=True)),
                ('send_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('save_at', models.DateTimeField(auto_now_add=True)),
                ('send_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('save_at', models.DateTimeField(auto_now_add=True)),
                ('send_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('save_at', models.DateTimeField(auto_now_add=True)),
                ('send_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebWebtoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('save_at', models.DateTimeField(auto_now_add=True)),
                ('send_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
