# Generated by Django 2.0.4 on 2018-05-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20180507_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webnews',
            old_name='content',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='webwebtoon',
            old_name='content',
            new_name='title',
        ),
        migrations.AddField(
            model_name='webmusic',
            name='singer',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
