# Generated by Django 2.0.4 on 2018-05-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_webmusic_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('save_at', models.DateTimeField(auto_now_add=True)),
                ('send_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ApiBus',
        ),
        migrations.DeleteModel(
            name='ApiMetro',
        ),
    ]
