# Generated by Django 2.0.4 on 2018-05-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_naversearch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='naversearch',
            old_name='level',
            new_name='link',
        ),
    ]
