# Generated by Django 2.0.4 on 2018-05-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_auto_20180522_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webdust',
            old_name='level',
            new_name='dust_level',
        ),
        migrations.RenameField(
            model_name='webdust',
            old_name='title',
            new_name='status',
        ),
        migrations.AddField(
            model_name='webdust',
            name='micro_dust_level',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
